services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./app/server/.env
    command: sh -c "redis-server --requirepass \"$$REDIS_PASSWORD\" --appendonly yes"

volumes:
  redis_data:
